// src/abi.ts

// --- SAADPresaleUSD_Pro ABI (from BaseScan — exactly what you provided) ---
export const SAAD_PRESALE_USD_PRO_ABI = [
  {
    "inputs":[
      {"internalType":"address","name":"_token","type":"address"},
      {"internalType":"address","name":"_usdt","type":"address"},
      {"internalType":"address","name":"_ethUsdFeed","type":"address"},
      {"internalType":"address","name":"_ethReceiver","type":"address"},
      {"internalType":"address","name":"_usdtReceiver","type":"address"},
      {"internalType":"uint256","name":"_p0","type":"uint256"},
      {"internalType":"uint256","name":"_p1","type":"uint256"},
      {"internalType":"uint256","name":"_p2","type":"uint256"}
    ],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {"inputs":[],"name":"ErrBadAddress","type":"error"},
  {"inputs":[],"name":"ErrBadOracle","type":"error"},
  {"inputs":[],"name":"ErrInvalidPhase","type":"error"},
  {"inputs":[],"name":"ErrNotEnoughInventory","type":"error"},
  {"inputs":[],"name":"ErrNotWhitelisted","type":"error"},
  {"inputs":[],"name":"ErrNothingToClaim","type":"error"},
  {"inputs":[],"name":"ErrPhaseCapExceeded","type":"error"},
  {"inputs":[],"name":"ErrPresaleEnded","type":"error"},
  {"inputs":[],"name":"ErrPresalePaused","type":"error"},
  {"inputs":[],"name":"ErrTooEarly","type":"error"},
  {"inputs":[],"name":"ErrZeroAmount","type":"error"},
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"user","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"Claimed",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},
      {"indexed":true,"internalType":"address","name":"newOwner","type":"address"}
    ],
    "name":"OwnershipTransferStarted",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},
      {"indexed":true,"internalType":"address","name":"newOwner","type":"address"}
    ],
    "name":"OwnershipTransferred",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":false,"internalType":"uint8","name":"newPhase","type":"uint8"},
      {"indexed":false,"internalType":"bool","name":"carriedOver","type":"bool"}
    ],
    "name":"PhaseAdvanced",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":false,"internalType":"uint8","name":"phase","type":"uint8"},
      {"indexed":false,"internalType":"uint256","name":"cap","type":"uint256"},
      {"indexed":false,"internalType":"uint64","name":"deadline","type":"uint64"},
      {"indexed":false,"internalType":"uint32","name":"priceUSDT6","type":"uint32"}
    ],
    "name":"PhaseUpdated",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":false,"internalType":"uint64","name":"claimStart","type":"uint64"},
      {"indexed":false,"internalType":"uint64","name":"cliff","type":"uint64"},
      {"indexed":false,"internalType":"uint64","name":"duration","type":"uint64"}
    ],
    "name":"PresaleEnded",
    "type":"event"
  },
  {"anonymous":false,"inputs":[],"name":"PresalePaused","type":"event"},
  {"anonymous":false,"inputs":[],"name":"PresaleResumed","type":"event"},
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"buyer","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"ethWei","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"usd6","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"tokens","type":"uint256"},
      {"indexed":false,"internalType":"uint8","name":"phase","type":"uint8"}
    ],
    "name":"PurchasedETH",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"buyer","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"usdt6","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"tokens","type":"uint256"},
      {"indexed":false,"internalType":"uint8","name":"phase","type":"uint8"}
    ],
    "name":"PurchasedUSDT",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":false,"internalType":"address","name":"ethReceiver","type":"address"},
      {"indexed":false,"internalType":"address","name":"usdtReceiver","type":"address"}
    ],
    "name":"ReceiversSet",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"token","type":"address"},
      {"indexed":true,"internalType":"address","name":"to","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"Swept",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"to","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"UnsoldWithdrawn",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"user","type":"address"},
      {"indexed":false,"internalType":"bool","name":"allowed","type":"bool"}
    ],
    "name":"WhitelistSet",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":false,"internalType":"bool","name":"required","type":"bool"}],
    "name":"WhitelistToggled",
    "type":"event"
  },
  {"inputs":[],"name":"TOKEN_DECIMALS","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"TOTAL_PHASES","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"USDT_DECIMALS","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"acceptOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"bool","name":"carryOverUnsold","type":"bool"}],"name":"advancePhase","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"buyWithETH","outputs":[],"stateMutability":"payable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"amountUSDT6","type":"uint256"}],"name":"buyWithUSDT","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"claim","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"claimStart","outputs":[{"internalType":"uint64","name":"","type":"uint64"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"claimed","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"cliffSeconds","outputs":[{"internalType":"uint64","name":"","type":"uint64"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"currentPhase","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},
  {
    "inputs":[
      {"internalType":"uint64","name":"_claimStart","type":"uint64"},
      {"internalType":"uint64","name":"_cliffSeconds","type":"uint64"},
      {"internalType":"uint64","name":"_vestingDuration","type":"uint64"}
    ],
    "name":"endPresaleAndStartVesting",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {"inputs":[],"name":"ethReceiver","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"ethUsdFeed","outputs":[{"internalType":"contract AggregatorV3Interface","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getEthUsd6","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"pause","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"paused","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"pendingOwner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {
    "inputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "name":"phases",
    "outputs":[
      {"internalType":"uint256","name":"cap","type":"uint256"},
      {"internalType":"uint256","name":"sold","type":"uint256"},
      {"internalType":"uint64","name":"deadline","type":"uint64"},
      {"internalType":"uint32","name":"priceUSDT6","type":"uint32"}
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {"inputs":[],"name":"presaleEnded","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint8","name":"p","type":"uint8"}],"name":"pricePerTokenUSDT","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"purchased","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"raisedETHWei","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"raisedUSDT6","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint8","name":"p","type":"uint8"}],"name":"remainingInPhase","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"resume","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint8","name":"p","type":"uint8"},{"internalType":"uint256","name":"cap","type":"uint256"}],"name":"setPhaseCap","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint8","name":"p","type":"uint8"},{"internalType":"uint64","name":"deadline","type":"uint64"}],"name":"setPhaseDeadline","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint8","name":"p","type":"uint8"},{"internalType":"uint32","name":"price6","type":"uint32"}],"name":"setPhasePrice","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"_ethReceiver","type":"address"},{"internalType":"address","name":"_usdtReceiver","type":"address"}],"name":"setReceivers","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address[]","name":"users","type":"address[]"},{"internalType":"bool","name":"allowed","type":"bool"}],"name":"setWhitelist","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"bool","name":"value","type":"bool"}],"name":"setWhitelistRequired","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"_token","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"sweepERC20","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address payable","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"sweepETH","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"token","outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"totalClaimed","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"totalPurchased","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"usdt","outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"usdtReceiver","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"vestingDuration","outputs":[{"internalType":"uint64","name":"","type":"uint64"}],"stateMutability":"view","type":"function"},
  {
    "inputs":[{"internalType":"address","name":"user","type":"address"}],
    "name":"vestingInfo",
    "outputs":[
      {"internalType":"uint256","name":"total","type":"uint256"},
      {"internalType":"uint256","name":"alreadyClaimed","type":"uint256"},
      {"internalType":"uint256","name":"unlocked","type":"uint256"},
      {"internalType":"uint256","name":"claimable","type":"uint256"},
      {"internalType":"uint64","name":"_claimStart","type":"uint64"},
      {"internalType":"uint64","name":"_cliff","type":"uint64"},
      {"internalType":"uint64","name":"_duration","type":"uint64"}
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {"inputs":[],"name":"whitelistRequired","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"whitelisted","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"withdrawUnsold","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"stateMutability":"payable","type":"receive"}
];

// --- Minimal ERC-20 ABI used by the frontend ---
export const ERC20_MIN_ABI = [
  {"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"type":"function"},
  {"constant":true,"inputs":[{"name":"owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"type":"function"},
  {"constant":true,"inputs":[{"name":"owner","type":"address"},{"name":"spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"type":"function"},
  {"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"type":"function"},
  {"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"type":"function"}
];
